### PR TITLE
add compatibility for angular#1.3.x

### PR DESCRIPTION
**Pull request by naeramarth7**
This fixes the error in angular 1.3.x and makes the controller available in compile and link methods - unsing angulars build in angular.extend method. Works with 1.2.24 as well.

[Demo](http://plnkr.co/edit/CJw5ZIO1vXdNSMPQiyXp?p=preview) | [Reference](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#since-1217-and-130-beta10) (section: $compile).

### CODE REVIEW

**Comment by soyuka** [comment]
this is better than #103 and indeed fixes this.

**Comment by mikcox** [comment]
+1 on this for sure, and the fix is better than #103.

**Comment by brandonrobertz** [comment]
Voting for this as well. Better than #103

**Comment by Briareos** [comment]
:+1:

**Comment by mtomov** [comment]
Please merge and release a new version with it. Thank you.

Updated: Thanks for the fix and the merge!

**Comment by Pasvaz** [comment]
Thank you @naeramarth7

**Comment by naeramarth7** [comment]
You're welcome @Pasvaz (:

**Pull request merged**
