### PR TITLE
This fix the angular 1.3 rc break.

### PR DESCRIPTION
**Pull request by TomerAvni**
Since 1.3 rc (actual 1.2.19), you cannot override the directive's controller, but rather extending it.
See https://github.com/angular/angular.js/issues/8876 for more info.

### CODE REVIEW

**Comment by TomerAvni** [comment]
This small fix enable the usage of angular 1.3rc.

**Comment by mikcox** [comment]
Wouldn't it be lighter-weight to use angular.extend instead of $.extend?  I recommend merging #104 instead of this one, it makes the same fix while only using built-in angular functionality.

**Comment by camwes** [comment]
+1

**Comment by Pasvaz** [comment]
Fixed by bdfc43b59591d64a9f0b9c9991513b2231cb84be

**Pull request closed without merging**
