### PR TITLE
added 'for' attribute

### PR DESCRIPTION
**Pull request by builtbylane**
as in `<label bo-for="foo">Foo<label>`

### CODE REVIEW

**Comment by Pasvaz** [comment]
Why it can't just be `<label bo-attr-for="foo">Foo<label>` ?

**Comment by builtbylane** [comment]
I will test this out next time I'm using the library. I often need to rely on `<label for="uniqueID"></label>` for things like custom checkboxes. will `<label bo-attr-for="foo">Foo<label>`  be treated as `<label for="foo"></label>`  by the browser or will it be treated as `<label attr-for="foo"></label>` ?

**Comment by Pasvaz** [comment]
`bo-attr-for="foo"` is translated as `for="foo"`. 
You can test it and let us know if everything works as expected.

**Comment by titomb345** [comment]
'bo-attr-for' is not working for me. Can we get this commit merged into the build? It's a simple fix that allows me to use bindonce for the labels on my custom radioswitches and checkboxes.

**Pull request closed without merging**
