### PR TITLE
Added bo-data for custom data attributes

### PR DESCRIPTION
**Pull request by aputinski**
Feel free to implement this however you would like, but I needed data attribute support for my app and this seemed to work well.

### CODE REVIEW

**Comment by spacenick** [comment]
Was actually going to write it as well, nice!

**Comment by Dema** [comment]
I think it would be better to change /^boData/ to /^bo/ in following condition

if (attrKey.match(/^boData/) && binder.attrs[attrKey]) 

This way you can replace any attribute like name=, min=, max=, type and other. 

Actually I'm fighting with the problem of 1500-3000 watchers in page (very complex forms generated from server-side json data) and need this feature...

**Comment by Pasvaz** [comment]
I apologize for not joining this conversation before but I'm still on vacation and I'll be operative asap. I can't test it right now so I could be wrong however I agree with @Dema bo-\* or even bot-attr-\* looks better than bo-data-*.
With bo-attr you could use `bo-attr-foo="bar"` to get `foo="bar"` and `bo-attr-data-foo="bar"` to get `data-foo="bar"`. 
Let me know what you think about it. 
I'll test this as soon as I'll get a pc where I can develop.

**Comment by aputinski** [comment]
@Pasvaz I think `bo-attr` makes sense and allows separation from the other built in binders.

**Comment by Pasvaz** [comment]
can you edit this PR in order to use bo-attr?

**Comment by aputinski** [comment]
I'll refactor in the next few days and resubmit

**Comment by Pasvaz** [comment]
Thank you for your contribution.

**Comment by louisremi** [comment]
I need this too! Seems like a perfect timing.

**Comment by Pasvaz** [comment]
This PR was merged as #19

**Comment by klwemu** [comment]
Okay but now i am not able to "bo" a data-key attribut?  Or??

When I have ...  data-key="{{record.key}}"  
Is there a "bo-" solution possible? And how?

Regards klaus

**Comment by Pasvaz** [comment]
use `<ANY bo-attr bo-attr-data-key="record.key">`

**Comment by martijnsenden** [comment]
Great! Is it possible to do this: `<ANY bo-attr bo-attr-foo="bar" bo-attr-soo="sar">` to get: `<ANY foo="bar" soo="sar">`?

**Comment by aputinski** [comment]
@martijnsenden Yes, that should work.

**Pull request closed without merging**
