### PR TITLE
Consume binders array as we process it.

### PR DESCRIPTION
**Pull request by ctucker**
Ensures that we both process newly added binders from bo-if, and that
we only process each binder once.

Address issue #25

### CODE REVIEW

**Comment by Pasvaz** [comment]
@ctucker sorry for letting you wait, I had to work on something else and only now I can spend some time on bindonce.
This PR could save a small amount of memory but it removes all the binders and while it seems logical to delete them after the binding process it breaks some directives. Specifically there are at least two breaks, one is the 'late binding', it occurs when `bindonce` is not the direct parent of the `bo-*` directives (it is an undocumented feature) and another case it's related to a new directive that I'm going to push soon that is named `onewatcher`.

**Comment by ctucker** [comment]
This wasn't to address a perceived memory issue, it was because failing to consume the array as we process it leads to incorrect behavior in the bo-if case.  The loop that traversed the binders goes up to a fixed index, so did not take note of newly added bindings, resulting in the issues documented in issue #25.  An alternative fix would be to not pre-compute max in the for initialization and instead do it per-loop, though obviously then care would have to be taken to only ever add binders to the end of the array (don't remember the code well enough to know if that property holds).  If it's becoming necessary to retain the binders after binding with your new features then naturally deleting them is not going to be the way to go. :-)

**Comment by Pasvaz** [comment]
Good point, I erroneously thought it was to save a bit of memory. I apologize for underestimating the potentials of this PR. However as I said before, it can't be done this way. None the less is a good tip.

**Comment by Pasvaz** [comment]
I checked the current code and actually the binders are emptied anyway, so this PR can be merged and when I'll push the new version it'll be substituted by the new method.

**Comment by Pasvaz** [comment]
If you rebase this PR I'll merge it

**Pull request merged**
